#!/usr/bin/env python3
"""Convert an 8x16 PSF console font into kernel/font.c (ASCII 0-127).

Default source: Terminus (SIL Open Font License 1.1), as shipped in
console-setup-linux: /usr/share/consolefonts/Lat15-Terminus16.psf.gz
"""
import gzip, sys

src = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/consolefonts/Lat15-Terminus16.psf.gz"
out = sys.argv[2] if len(sys.argv) > 2 else "kernel/font.c"
data = gzip.open(src).read() if src.endswith(".gz") else open(src, "rb").read()

if data[:2] == b"\x36\x04":                      # PSF1
    mode, h = data[2], data[3]
    count, hdr, w = (512 if mode & 1 else 256), 4, 8
    has_tab = mode & 2
    glyphs = [data[hdr + i*h: hdr + (i+1)*h] for i in range(count)]
    tab = data[hdr + count*h:]
    cmap, g, i = {}, 0, 0
    while has_tab and i + 1 < len(tab) and g < count:
        v = tab[i] | tab[i+1] << 8; i += 2
        if v == 0xFFFF: g += 1
        elif v != 0xFFFE: cmap.setdefault(v, g)
elif data[:4] == b"\x72\xb5\x4a\x86":            # PSF2
    import struct
    _, _, hdr, flags, count, size, h, w = struct.unpack("<8I", data[:32])
    assert w == 8, "only 8-pixel-wide fonts supported"
    glyphs = [data[hdr + i*size: hdr + (i+1)*size] for i in range(count)]
    tab = data[hdr + count*size:]
    cmap, g, i = {}, 0, 0
    while flags & 1 and i < len(tab) and g < count:
        b = tab[i]
        if b == 0xFF: g += 1; i += 1; continue
        if b == 0xFE: i += 1; continue
        n = 1 if b < 0x80 else 2 if b < 0xE0 else 3 if b < 0xF0 else 4
        cmap.setdefault(ord(tab[i:i+n].decode("utf-8", "replace")), g); i += n
else:
    sys.exit("not a PSF font")

assert h == 16, "expected an 8x16 font"
with open(out, "w") as f:
    f.write("/* Generated by tools/mkfont.py from Terminus 8x16 (SIL OFL 1.1). */\n")
    f.write('#include "font.h"\n\nconst unsigned char font8x16[128][16] = {\n')
    for c in range(128):
        gl = glyphs[cmap.get(c, c)] if (c >= 32 and cmap) else (glyphs[c] if c >= 32 else bytes(16))
        f.write("    {" + ",".join("0x%02x" % b for b in gl[:16]) + "}, /* %d */\n" % c)
    f.write("};\n")
print("wrote", out)
